const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const charts={}; let DB={};
const unitLabel={percent:'%',per_mille:'‰',person:'人',million_ntd:'百萬元',thousand_ntd:'千元',index:'指數',index_2021_100:'110年=100',index_2016_100:'105年=100'};
function fmt(v,unit){if(v==null)return '—';if(unit==='person')return Number(v).toLocaleString('zh-TW',{maximumFractionDigits:0});if(unit==='million_ntd'&&v>1e6)return (v/1e6).toFixed(2)+' 兆';if(unit==='thousand_ntd'&&Math.abs(v)>1e8)return (v/1e8).toFixed(2)+' 千億元';return Number(v).toLocaleString('zh-TW',{maximumFractionDigits:2})+(unit==='percent'?'%':unit==='per_mille'?'‰':'')}
function latest(s){return s?.data?.length?s.data[s.data.length-1]:[null,null]}
function chart(id,config){if(charts[id])charts[id].destroy();charts[id]=new Chart($(id),config);return charts[id]}
function lineConfig(labels,datasets,opts={}){return{type:'line',data:{labels,datasets:datasets.map(d=>({...d,borderWidth:2,pointRadius:labels.length>45?0:2,tension:.18}))},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:datasets.length>1,position:'bottom'}},scales:{x:{ticks:{maxTicksLimit:12}},y:{beginAtZero:false}},...opts}}}
function downloadCSV(name,rows,headers=['period','value']){const esc=x=>'"'+String(x??'').replaceAll('"','""')+'"';const text='\ufeff'+[headers,...rows].map(r=>r.map(esc).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
async function load(){const st=await fetch('data/status.json?x='+Date.now(),{cache:'no-store'}).then(r=>r.json());const v=encodeURIComponent(st.last_check_at||Date.now());const [macro,pop,industry,coverage]=await Promise.all(['macro.json','population.json','industry.json','coverage.json'].map(f=>fetch('data/'+f+'?v='+v).then(r=>r.json())));DB={status:st,macro,pop,industry,coverage};render();$('#loading').classList.add('hidden')}
function render(){renderHealth();renderCards();renderOverview();setupMacro();setupPopulation();setupIndustry();renderCoverage();setupTabs()}
function renderHealth(){const st=DB.status, critical=['dgbas','moea','ris'].map(k=>st.sources[k]?.status);const bad=critical.some(x=>x!=='ok');const b=$('#healthBanner');b.className='health-banner '+(bad?'degraded':'ok');b.innerHTML=`<div><b>${bad?'部分來源本次更新異常，已保留上一版正確資料':'關鍵資料來源正常'}</b><div class="sub">最後檢查：${new Date(st.last_check_at).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})}</div></div><div class="tag">Pipeline v${st.pipeline_version}</div>`;$('#lastCheck').textContent='最後檢查 '+new Date(st.last_check_at).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'});$('#footerSync').textContent='Last check '+st.last_check_at;const names={dgbas:'主計總處來源',moea:'經濟部',ris:'戶政司',segis:'SEGIS'};$('#sourceCards').innerHTML=Object.entries(st.sources).map(([k,s])=>`<div class="source"><div class="top"><b>${names[k]||k}</b><span class="status ${s.status}">${s.status}</span></div><div class="meta">最新期間：${s.latest_period||'—'}<br>${s.message||''}</div></div>`).join('')}
function renderCards(){const m=DB.macro.series,p=DB.pop.national;const gdp=m['dgbas.gdp.nominal.production'],gr=m['dgbas.gdp.growth_rate'],cpi=m['dgbas.cpi.yoy'],pt=p['ris.pop.year_end_total'];const vals=[['名目 GDP',gdp],['經濟成長率',gr],['CPI 年增率',cpi],['年底人口',pt]];$('#headlineCards').innerHTML=vals.map(([label,s])=>{const [period,v]=latest(s);return `<div class="card"><div class="label">${label}</div><div class="value">${fmt(v,s.unit)}</div><div class="sub">${period||'—'} · ${unitLabel[s.unit]||s.unit}</div></div>`}).join('')}
function renderOverview(){const m=DB.macro.series,p=DB.pop.national;const g=m['dgbas.gdp.growth_rate'].data,c=m['dgbas.cpi.yoy'].data;const years=[...new Set([...g.map(x=>x[0]),...c.map(x=>x[0])])].sort();const map=a=>Object.fromEntries(a);chart('#overviewMacro',lineConfig(years,[{label:'經濟成長率 %',data:years.map(y=>map(g)[y]??null)},{label:'CPI 年增率 %',data:years.map(y=>map(c)[y]??null)}]));const pp=p['ris.pop.year_end_total'].data,old=p['ris.pop.share_65_plus'].data;const ys=[...new Set([...pp.map(x=>x[0]),...old.map(x=>x[0])])].sort();chart('#overviewPop',lineConfig(ys,[{label:'總人口（百萬）',data:ys.map(y=>(map(pp)[y]??null)/1e6),yAxisID:'y'},{label:'65+ 占比 %',data:ys.map(y=>map(old)[y]??null),yAxisID:'y1'}],{scales:{y:{position:'left'},y1:{position:'right',grid:{drawOnChartArea:false}},x:{ticks:{maxTicksLimit:10}}}}));$('#countyPeriod').textContent=DB.pop.latest_period||'—';$('#countyTable').innerHTML=DB.pop.county_latest.map(r=>`<tr><td>${r.name}</td><td>${r.population.toLocaleString()}</td><td>${r.age_0_14.toLocaleString()}</td><td>${r.age_65_plus.toLocaleString()}</td><td>${r.share_65_plus.toFixed(2)}%</td><td>${r.aging_index?.toFixed(1)??'—'}</td></tr>`).join('')}
function setupMacro(){const sel=$('#macroSelect');const entries=Object.entries(DB.macro.series).sort((a,b)=>a[1].name.localeCompare(b[1].name,'zh-Hant'));sel.innerHTML=entries.map(([id,s])=>`<option value="${id}">${s.name}</option>`).join('');sel.value=DB.macro.series['dgbas.gdp.growth_rate']?'dgbas.gdp.growth_rate':entries[0][0];const draw=()=>{const s=DB.macro.series[sel.value];chart('#macroChart',lineConfig(s.data.map(x=>x[0]),[{label:s.name,data:s.data.map(x=>x[1])}]));$('#macroRows').innerHTML=[...s.data].reverse().map(([p,v])=>`<tr><td>${p}</td><td>${fmt(v,s.unit)}</td><td>${unitLabel[s.unit]||s.unit}</td></tr>`).join('')};sel.onchange=draw;$('#macroCsv').onclick=()=>{const s=DB.macro.series[sel.value];downloadCSV(sel.value+'.csv',s.data,['period','value'])};draw()}
function setupPopulation(){const sel=$('#popSelect');const entries=Object.entries(DB.pop.national).sort((a,b)=>a[1].name.localeCompare(b[1].name,'zh-Hant'));sel.innerHTML=entries.map(([id,s])=>`<option value="${id}">${s.name}</option>`).join('');sel.value='ris.pop.year_end_total';const draw=()=>{const s=DB.pop.national[sel.value];chart('#popChart',lineConfig(s.data.map(x=>x[0]),[{label:s.name,data:s.data.map(x=>x[1])}]))};sel.onchange=draw;$('#popCsv').onclick=()=>{const s=DB.pop.national[sel.value];downloadCSV(sel.value+'.csv',s.data,['period','value'])};draw();const cs=$('#countySelect');const counties=Object.entries(DB.pop.county_history).sort((a,b)=>a[1].name.localeCompare(b[1].name,'zh-Hant'));cs.innerHTML=counties.map(([id,g])=>`<option value="${id}">${g.name}</option>`).join('');cs.value=DB.pop.county_history['65000']?'65000':counties[0][0];const cm=$('#countyMetric');const drawC=()=>{const g=DB.pop.county_history[cs.value],key=cm.value,labels=g.data.map(x=>x.period),data=g.data.map(x=>x[key]);const names={population:'總人口',share_65_plus:'65歲以上占比',aging_index:'老化指數'};chart('#countyChart',lineConfig(labels,[{label:g.name+' · '+names[key],data}]))};cs.onchange=cm.onchange=drawC;drawC()}
function datasetLabel(k,x){const map={'moea.industry.production':'工業生產指數','moea.manufacturing.sales_volume':'製造業銷售量指數','moea.manufacturing.sales_value':'製造業銷售價值','moea.manufacturing.investment':'製造業營業額與投資','moea.electronics.production_sales_inventory':'電子光學產銷存價值'};return map[k]||x.name||k}
function setupIndustry(){const ds=$('#industryDataset'),ss=$('#industrySeries');const entries=Object.entries(DB.industry.datasets);ds.innerHTML=entries.map(([k,x])=>`<option value="${k}">${datasetLabel(k,x)}</option>`).join('');ds.value=DB.industry.datasets['moea.industry.production']?'moea.industry.production':entries[0][0];const populate=()=>{const x=DB.industry.datasets[ds.value],series=x.series||{};ss.innerHTML=Object.entries(series).map(([k,s])=>`<option value="${k}">${s.name||k}</option>`).join('');if(series['I2'])ss.value='I2';else if(series['Z'])ss.value='Z';draw()};const draw=()=>{const x=DB.industry.datasets[ds.value],s=x.series[ss.value];if(!s)return;const unit=x.unit||s.unit||'value';chart('#industryChart',lineConfig(s.data.map(x=>x[0]),[{label:s.name||ss.value,data:s.data.map(x=>x[1])}]));$('#industryRows').innerHTML=[...s.data].reverse().slice(0,240).map(([p,v])=>`<tr><td>${p}</td><td>${fmt(v,unit)}</td><td>${unitLabel[unit]||unit}</td></tr>`).join('')};ds.onchange=populate;ss.onchange=draw;$('#industryCsv').onclick=()=>{const x=DB.industry.datasets[ds.value],s=x.series[ss.value];downloadCSV(ds.value+'-'+ss.value+'.csv',s.data,['period','value'])};populate()}
function renderCoverage(){const rows=DB.coverage.datasets||[];$('#coverageRows').innerHTML=rows.map(r=>`<tr><td>${r.source}</td><td>${r.dataset||'—'}</td><td>${r.name||r.indicator}</td><td>${Number(r.points||0).toLocaleString()}</td><td>${r.period||'—'}</td></tr>`).join('')}
function setupTabs(){$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.tab').forEach(s=>s.classList.toggle('active',s.id===b.dataset.tab));setTimeout(()=>Object.values(charts).forEach(c=>c.resize()),50)})}
load().catch(e=>{console.error(e);$('#loading').innerHTML=`<div><b>資料載入失敗</b><br><small>${String(e)}</small></div>`});
