(()=>{
const q=s=>document.querySelector(s);
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=v=>v==null?'—':`${Number(v)>=0?'+':''}${Number(v).toFixed(1)}%`;
const num=v=>v==null?'—':Number(v).toLocaleString('zh-TW',{maximumFractionDigits:2});
const cls=v=>v==null?'alpha-neutral':Number(v)>0?'alpha-positive':Number(v)<0?'alpha-negative':'alpha-neutral';
const actionClass=v=>String(v||'').toLowerCase().replaceAll(' ','-').replaceAll('_','-');
const contextName={BROADLY_SUPPORTIVE:'廣泛支持',EXPORT_LED_SUPPORTIVE:'出口／科技支持',CONSTRUCTIVE:'偏正向',MIXED:'混合',DEFENSIVE:'防禦',UNKNOWN:'資料不足'};
function linkCss(href){if(!q(`link[href="${href}"]`)){const l=document.createElement('link');l.rel='stylesheet';l.href=href;document.head.appendChild(l)}}
function ensureShell(){
 linkCss('investment.css');linkCss('capital.css');
 const tabs=q('.tabs');if(tabs&&!q('[data-tab="investment"]')){const b=document.createElement('button');b.dataset.tab='investment';b.textContent='投資／Alpha';const health=q('[data-tab="health"]');tabs.insertBefore(b,health||null)}
 if(q('#investment'))return;
 const s=document.createElement('section');s.id='investment';s.className='tab';s.innerHTML=`
 <div class="investment-hero">
  <article class="panel"><div class="panel-head"><div><span class="kicker">MACRO × ALPHA</span><h2>Investment Context</h2><p class="sub">Macro 只提供 regime；不修改 Alpha Score 或 Buy Gate。</p></div><span id="investmentStatus" class="investment-status">—</span></div><h3 id="investmentContextLabel">—</h3><p id="investmentContextText" class="sub">載入…</p><div id="investmentMetrics" class="investment-context"></div></article>
  <article class="panel"><div class="panel-head"><div><span class="kicker">OPPORTUNITY COST</span><h2>Benchmark</h2></div></div><div id="investmentBenchmark">—</div><div class="investment-rule"><strong>核心規則</strong><p>TSMC 3000 只是重新評估事件；任何 rotation 都必須先勝過可用 opportunity hurdle。</p></div></article>
 </div>
 <article class="panel"><div class="panel-head controls-head"><div><span class="kicker">CAPITAL ALLOCATION OS</span><h2>這一塊錢該放哪裡？</h2><p class="sub">Opportunity Set → Probabilistic ER → Lifecycle → Portfolio Risk → Sizing。</p></div><span id="capitalStatus" class="tag">—</span></div><div id="capitalCards" class="capital-cards"></div><div class="capital-grid"><div><h3>Opportunity Set</h3><div id="opportunityRows" class="capital-list"></div></div><div><h3>Portfolio / Risk</h3><div id="portfolioRisk">—</div></div></div></article>
 <article class="panel"><div class="panel-head"><div><span class="kicker">POSITION LIFECYCLE</span><h2>BUY / ADD / HOLD / TRIM / EXIT</h2></div></div><div class="table-wrap"><table class="capital-table"><thead><tr><th>股票</th><th>Upstream</th><th>Portfolio</th><th>ER</th><th>Hurdle</th><th>Net Alpha</th><th>原因</th></tr></thead><tbody id="capitalLifecycle"></tbody></table></div></article>
 <article class="panel"><div class="panel-head"><div><span class="kicker">PROBABILISTIC RETURN</span><h2>Scenario Distribution</h2></div></div><div class="table-wrap"><table><thead><tr><th>股票</th><th>Archetype</th><th>Expected</th><th>Beat Hurdle</th><th>P(loss &gt;20%)</th><th>Downside ES</th></tr></thead><tbody id="probReturnRows"></tbody></table></div></article>
 <article class="panel"><div class="panel-head"><div><span class="kicker">ALPHA ENGINE</span><h2>已研究個股與 Buy Gate</h2><p id="investmentSelectionText" class="sub">載入 Alpha research…</p></div><div><span id="investmentFreshness" class="alpha-sub"></span></div></div><div class="table-wrap"><table class="alpha-table"><thead><tr><th>#</th><th>個股</th><th>Alpha</th><th>Confidence</th><th>Action</th><th>參考價</th><th>預期報酬</th><th>vs TSMC</th><th>MOS / Next</th></tr></thead><tbody id="alphaRankingRows"></tbody></table></div></article>
 <article class="panel"><div class="panel-head"><div><span class="kicker">FULL MARKET SCREEN</span><h2>全市場 Top 10 Discovery</h2><p class="sub">Screen 只能產生研究候選，不能直接 BUY。</p></div></div><div class="table-wrap"><table><thead><tr><th>#</th><th>公司</th><th>市場</th><th>價格</th><th>營收 YoY</th><th>TTM PE</th><th>Priority</th><th>研究狀態</th></tr></thead><tbody id="alphaScreenRows"></tbody></table></div></article>
 <article class="panel"><div class="panel-head"><div><span class="kicker">DEEP RESEARCH AUTOMATION</span><h2>研究佇列</h2></div></div><div id="deepResearchGrid" class="deep-grid"></div><div id="capitalResearchQueue" class="capital-list"></div></article>
 <article class="panel"><div class="panel-head"><div><span class="kicker">CLOSED LOOP</span><h2>Calibration</h2></div></div><div id="alphaCalibration">—</div></article>
 <article class="notice"><strong>邊界</strong><p>Macro ≠ Alpha；Screen ≠ BUY；Portfolio Engine 不能把 VERIFY/WATCH 升成 BUY；未配置當前持倉時，不輸出個人 target weight；永不自動交易。</p></article>`;
 const health=q('#health');(health?.parentNode||q('main')).insertBefore(s,health||null)
}
function metric(label,x){return `<div class="investment-metric"><div class="label">${esc(label)}</div><div class="value">${x?.score==null?'—':Number(x.score).toFixed(0)}</div><div class="period">${esc(x?.label||'—')} · ${esc(x?.period||'—')}</div></div>`}
function renderInvestment(data){
 const st=q('#investmentStatus');st.textContent=data.status;st.className=`investment-status ${String(data.status||'').toLowerCase()}`;const m=data.macro_context||{};q('#investmentContextLabel').textContent=contextName[m.label]||m.label||'—';q('#investmentContextText').textContent=m.text||'—';q('#investmentMetrics').innerHTML=[['Cycle',m.cycle],['Growth Persistence',m.growth_persistence],['Domestic Demand',m.domestic_demand],['Financial Conditions',m.financial_conditions]].map(([a,b])=>metric(a,b)).join('');
 const b=data.benchmark||{};q('#investmentBenchmark').innerHTML=`<div class="value">${esc(b.ticker)} ${esc(b.name)}</div><div class="alpha-sub">參考價 ${num(b.reference_price)} · ${esc(b.reference_price_date)}<br>模型預期報酬 <b class="${cls(b.expected_return_pct)}">${pct(b.expected_return_pct)}</b> · Confidence ${num(b.confidence_score)}</div>`;
 const src=data.sources||{},fresh=data.freshness||{};q('#investmentFreshness').innerHTML=`Research ${esc(src.alpha_research_as_of)} (${fresh.alpha_research_age_days??'—'}d)<br>Screen ${esc(src.screen_as_of)} (${fresh.screen_age_days??'—'}d) · <b>${esc(src.screen_status)}</b>`;q('#investmentSelectionText').textContent=data.selection?.text||'—';
 const rows=data.selection?.researched||[];q('#alphaRankingRows').innerHTML=rows.map(r=>`<tr><td>${esc(r.rank)}</td><td><b>${esc(r.ticker)} ${esc(r.name)}</b><div class="alpha-sub">${esc(r.thesis||'')}</div></td><td><span class="alpha-score">${num(r.score)}</span> / ${esc(r.grade)}</td><td>${num(r.confidence_score)}</td><td><span class="alpha-action ${actionClass(r.action)}">${esc(r.action)}</span></td><td>${num(r.reference_price)}<div class="alpha-sub">${esc(r.reference_price_date)}</div></td><td class="${cls(r.expected_return_pct)}">${pct(r.expected_return_pct)}</td><td class="${cls(r.alpha_spread_pct)}">${pct(r.alpha_spread_pct)}</td><td>${r.margin_of_safety_pct==null?'—':pct(r.margin_of_safety_pct)}<div class="alpha-sub">${esc(r.next_check||'')}</div></td></tr>`).join('')||'<tr><td colspan="9">尚無 Alpha research</td></tr>';
 const sc=data.selection?.top_screen||[];q('#alphaScreenRows').innerHTML=sc.map(r=>`<tr><td>${esc(r.rank)}</td><td><b>${esc(r.ticker)} ${esc(r.name)}</b></td><td>${esc(r.market)}</td><td>${num(r.reference_price)}</td><td>${pct(r.revenue_yoy_pct)}</td><td>${num(r.pe_ttm)}</td><td>${num(r.screen_priority)}</td><td>${r.deep_research_selected?'Deep Research':'Screen'}</td></tr>`).join('')||'<tr><td colspan="8">尚無 Screen</td></tr>';
 const deep=data.selection?.deep_research_queue||[];q('#deepResearchGrid').innerHTML=deep.slice(0,12).map((r,i)=>`<div class="deep-card"><b>#${esc(r.rank??i+1)} ${esc(r.ticker)} ${esc(r.name||'')}</b><span>${esc(r.market||'')} ${r.screen_priority!=null?`· priority ${num(r.screen_priority)}`:''}</span></div>`).join('');
 const cal=data.calibration||{},cm=cal.meta||{};q('#alphaCalibration').innerHTML=`Alpha performance：<b>${esc(cm.status||'—')}</b> · BUY samples ${num(cm.primary_entry_count)} / ${num(cal.minimum_samples_for_calibration)}。樣本不足時不宣稱已驗證。`;
}
function renderCapital(d){
 q('#capitalStatus').textContent=d.status||'—';const o=d.opportunity_set||{},risk=d.portfolio_risk||{},sz=d.target_sizing||{},rq=d.research_queue||{};q('#capitalCards').innerHTML=[['Hurdle',o.hurdle_asset?`${esc(o.hurdle_asset)} · ${pct(o.hurdle_expected_return_pct)}`:'—'],['Research Queue',`${(rq.items||[]).length} · new ${rq.new_research_count??0}`],['Portfolio State',esc(d.portfolio_state_status)],['Sizing',esc(sz.status)]].map(([a,b])=>`<div class="capital-card"><div class="label">${a}</div><div class="value">${b}</div></div>`).join('');
 q('#opportunityRows').innerHTML=(o.alternatives||[]).map(x=>`<div class="capital-item"><div><b>${esc(x.id)} ${esc(x.name)}</b><div class="capital-muted">${esc(x.source)}</div></div><div><span class="capital-pill ${x.status==='AVAILABLE'?'capital-good':'capital-muted'}">${esc(x.status)}</span><br>${pct(x.expected_return_pct)}</div></div>`).join('');
 q('#portfolioRisk').innerHTML=`<b>${esc(risk.status)}</b><p class="capital-muted">${esc(risk.note||'')}</p>${risk.personalized?`<div>Violations: ${(risk.violations||[]).length}</div><div class="prob-grid">${(risk.stress_tests||[]).map(x=>`<div class="prob-box"><b>${pct(x.market_shock_pct)}</b><br>Portfolio ${pct(x.portfolio_impact_pct)}<br>Post debt ${pct(x.post_shock_debt_ratio_pct)}</div>`).join('')}</div>`:'<div>填入最新 portfolio_state 後才會產生個人化 concentration / leverage / stress。</div>'}`;
 q('#capitalLifecycle').innerHTML=(d.lifecycle||[]).map(x=>`<tr><td><b>${esc(x.ticker)} ${esc(x.name)}</b></td><td>${esc(x.upstream_action)}</td><td><span class="capital-pill">${esc(x.portfolio_action)}</span></td><td>${pct(x.expected_return_pct)}</td><td>${pct(x.hurdle_expected_return_pct)}</td><td class="${cls(x.net_alpha_spread_pct)}">${pct(x.net_alpha_spread_pct)}</td><td>${esc(x.reason)}</td></tr>`).join('')||'<tr><td colspan="7">—</td></tr>';
 q('#probReturnRows').innerHTML=(d.probabilistic_returns||[]).map(x=>{const z=x.distribution||{};return `<tr><td><b>${esc(x.ticker)} ${esc(x.name)}</b></td><td>${esc(x.archetype)}</td><td>${pct(z.expected_return_pct)}</td><td>${pct(z.probability_beating_hurdle_pct)}</td><td>${pct(z.probability_loss_gt_20_pct)}</td><td>${pct(z.expected_shortfall_pct)}</td></tr>`}).join('');
 q('#capitalResearchQueue').innerHTML=(rq.items||[]).map(x=>`<div class="capital-item"><div><b>${esc(x.ticker)} ${esc(x.name)}</b><div class="capital-muted">${esc(x.archetype)} · ${esc(x.status)}</div></div><div>${esc(x.next_action)}</div></div>`).join('');
}
async function init(){ensureShell();try{const [ir,cr]=await Promise.all([fetch(`data/investment.json?x=${Date.now()}`,{cache:'no-store'}),fetch(`data/capital_allocation.json?x=${Date.now()}`,{cache:'no-store'})]);if(!ir.ok)throw new Error(`investment HTTP ${ir.status}`);renderInvestment(await ir.json());if(cr.ok)renderCapital(await cr.json());else q('#capitalStatus').textContent='UNAVAILABLE'}catch(e){console.error('investment layer',e);const el=q('#investmentSelectionText');if(el)el.textContent=`Investment layer 載入失敗：${String(e)}`}}
init();
})();
