#!/usr/bin/env python3
from __future__ import annotations
import json
from common import load_json,save_json
FACTORS=['TAIWAN_MARKET','SEMICONDUCTOR','AI_CAPEX','MEMORY_CYCLE','RATE','USD_TWD','CHINA_DEMAND','GLOBAL_TECH','LIQUIDITY']
BASE={
 'BENCHMARK':{'TAIWAN_MARKET':1.0,'SEMICONDUCTOR':1.0,'AI_CAPEX':0.75,'MEMORY_CYCLE':0.25,'RATE':-0.15,'USD_TWD':0.35,'CHINA_DEMAND':0.15,'GLOBAL_TECH':0.8,'LIQUIDITY':0.05},
 'SECULAR_GROWTH':{'TAIWAN_MARKET':1.0,'SEMICONDUCTOR':0.45,'AI_CAPEX':0.9,'MEMORY_CYCLE':0.15,'RATE':-0.2,'USD_TWD':0.3,'CHINA_DEMAND':0.1,'GLOBAL_TECH':0.85,'LIQUIDITY':0.1},
 'CYCLICAL_MEMORY':{'TAIWAN_MARKET':1.1,'SEMICONDUCTOR':0.75,'AI_CAPEX':0.4,'MEMORY_CYCLE':1.0,'RATE':-0.15,'USD_TWD':0.3,'CHINA_DEMAND':0.35,'GLOBAL_TECH':0.7,'LIQUIDITY':0.2},
 'UTILITY':{'TAIWAN_MARKET':0.55,'SEMICONDUCTOR':0.0,'AI_CAPEX':0.1,'MEMORY_CYCLE':0.0,'RATE':-0.45,'USD_TWD':0.05,'CHINA_DEMAND':0.05,'GLOBAL_TECH':0.1,'LIQUIDITY':0.15},
 'PROPERTY':{'TAIWAN_MARKET':0.75,'SEMICONDUCTOR':0.0,'AI_CAPEX':0.0,'MEMORY_CYCLE':0.0,'RATE':-0.8,'USD_TWD':0.0,'CHINA_DEMAND':0.15,'GLOBAL_TECH':0.0,'LIQUIDITY':0.3},
 'GENERAL_INDUSTRIAL':{'TAIWAN_MARKET':0.85,'SEMICONDUCTOR':0.15,'AI_CAPEX':0.2,'MEMORY_CYCLE':0.1,'RATE':-0.2,'USD_TWD':0.15,'CHINA_DEMAND':0.35,'GLOBAL_TECH':0.2,'LIQUIDITY':0.25},
 'ASSET_NAV':{'TAIWAN_MARKET':0.7,'SEMICONDUCTOR':0.0,'AI_CAPEX':0.0,'MEMORY_CYCLE':0.0,'RATE':-0.35,'USD_TWD':0.0,'CHINA_DEMAND':0.1,'GLOBAL_TECH':0.0,'LIQUIDITY':0.3},
 'FINANCIAL':{'TAIWAN_MARKET':0.85,'SEMICONDUCTOR':0.0,'AI_CAPEX':0.0,'MEMORY_CYCLE':0.0,'RATE':0.5,'USD_TWD':0.0,'CHINA_DEMAND':0.2,'GLOBAL_TECH':0.0,'LIQUIDITY':0.1}}
VOL={'TAIWAN_MARKET':22,'SEMICONDUCTOR':28,'AI_CAPEX':32,'MEMORY_CYCLE':38,'RATE':6,'USD_TWD':8,'CHINA_DEMAND':18,'GLOBAL_TECH':24,'LIQUIDITY':16}
PAIR={('TAIWAN_MARKET','SEMICONDUCTOR'):.72,('TAIWAN_MARKET','AI_CAPEX'):.60,('TAIWAN_MARKET','MEMORY_CYCLE'):.55,('TAIWAN_MARKET','GLOBAL_TECH'):.62,('SEMICONDUCTOR','AI_CAPEX'):.72,('SEMICONDUCTOR','MEMORY_CYCLE'):.68,('AI_CAPEX','GLOBAL_TECH'):.78,('MEMORY_CYCLE','GLOBAL_TECH'):.55,('RATE','TAIWAN_MARKET'):-.18,('USD_TWD','TAIWAN_MARKET'):-.25,('CHINA_DEMAND','TAIWAN_MARKET'):.35}
ALT={'2330':BASE['BENCHMARK'],'TAIWAN_BROAD':{'TAIWAN_MARKET':1.0,'SEMICONDUCTOR':0.55,'AI_CAPEX':0.45,'MEMORY_CYCLE':0.2,'RATE':-0.15,'USD_TWD':0.2,'CHINA_DEMAND':0.15,'GLOBAL_TECH':0.45,'LIQUIDITY':0.04},'GLOBAL_EQUITY':{'TAIWAN_MARKET':0.08,'SEMICONDUCTOR':0.2,'AI_CAPEX':0.28,'MEMORY_CYCLE':0.12,'RATE':-0.18,'USD_TWD':-0.35,'CHINA_DEMAND':0.18,'GLOBAL_TECH':0.72,'LIQUIDITY':0.03},'CASH':{k:0.0 for k in FACTORS}}
STRESS={'GLOBAL_TECH_CRASH':{'TAIWAN_MARKET':-25,'SEMICONDUCTOR':-35,'AI_CAPEX':-45,'MEMORY_CYCLE':-30,'RATE':2,'USD_TWD':-3,'CHINA_DEMAND':-10,'GLOBAL_TECH':-40,'LIQUIDITY':-25},'TAIWAN_CRASH':{'TAIWAN_MARKET':-35,'SEMICONDUCTOR':-30,'AI_CAPEX':-25,'MEMORY_CYCLE':-25,'RATE':1,'USD_TWD':8,'CHINA_DEMAND':-10,'GLOBAL_TECH':-12,'LIQUIDITY':-35},'AI_CAPEX_BUST':{'TAIWAN_MARKET':-18,'SEMICONDUCTOR':-25,'AI_CAPEX':-50,'MEMORY_CYCLE':-22,'RATE':-1,'USD_TWD':3,'CHINA_DEMAND':-5,'GLOBAL_TECH':-20,'LIQUIDITY':-20},'MEMORY_COLLAPSE':{'TAIWAN_MARKET':-12,'SEMICONDUCTOR':-18,'AI_CAPEX':-8,'MEMORY_CYCLE':-55,'RATE':0,'USD_TWD':2,'CHINA_DEMAND':-10,'GLOBAL_TECH':-8,'LIQUIDITY':-18},'RATES_PLUS_200BP':{'TAIWAN_MARKET':-12,'SEMICONDUCTOR':-10,'AI_CAPEX':-10,'MEMORY_CYCLE':-8,'RATE':2,'USD_TWD':-2,'CHINA_DEMAND':-5,'GLOBAL_TECH':-10,'LIQUIDITY':-8}}
def corr(a,b):return 1.0 if a==b else PAIR.get((a,b),PAIR.get((b,a),0.10))
def generate():
 facts=load_json('security_fact_store.json',{});rows=[]
 for s in facts.get('securities',[]):
  arch='BENCHMARK' if s.get('stage')=='BENCHMARK' else s.get('archetype','GENERAL_INDUSTRIAL');rows.append({'ticker':s.get('ticker'),'name':s.get('name'),'stage':s.get('stage'),'archetype':arch,'factor_loadings':BASE.get(arch,BASE['GENERAL_INDUSTRIAL']),'reference_price':s.get('reference_price'),'reference_price_date':s.get('reference_price_date'),'idiosyncratic_vol_pct':10 if arch=='BENCHMARK' else 18})
 cov={a:{b:round(VOL[a]*VOL[b]*corr(a,b)/10000,6) for b in FACTORS} for a in FACTORS}
 out={'version':1,'status':'MODEL_ASSUMPTION','factors':FACTORS,'factor_volatility_pct':VOL,'factor_correlation':{f'{a}|{b}':corr(a,b) for i,a in enumerate(FACTORS) for b in FACTORS[i:]},'factor_covariance':cov,'security_loadings':rows,'alternative_loadings':ALT,'stress_scenarios':STRESS,'human_capital_profiles':{'TAIWAN_TECH':{'TAIWAN_MARKET':0.6,'SEMICONDUCTOR':0.45,'AI_CAPEX':0.35,'GLOBAL_TECH':0.35,'USD_TWD':0.1},'TAIWAN_GENERAL':{'TAIWAN_MARKET':0.35,'CHINA_DEMAND':0.15},'LOW_CORRELATION':{}},'guardrail':'Transparent structural factor assumptions; personal weights and optimizer never leave browser localStorage.'};save_json('portfolio_model.json',out);return out
if __name__=='__main__':print(json.dumps(generate(),ensure_ascii=False,indent=2))
